GET http://localhost:5000/api/items

###

GET http://localhost:5000/api/items/1

###

POST http://localhost:5000/api/items

###

PUT http://localhost:5000/api/items/1

###

DELETE http://localhost:5000/api/items/1